In [1]:
import pandas as pd
import requests

# Fetch the data.
df1 = pd.read_csv("sdgi-9-1-1-rai-2023-subnational.csv")

df1.head()

,OID,ISO3,NAME_0,NAME_1,NAME_2,Pop_A2,Pop_A2_R,Pop_A2_R2K,SDG911pct,Pct_Error,Shape_Leng,Shape_Area
0,-1,ABW,Aruba,,,106242.963168,8123.699344,8123.066945,99.992215,0.489891,0.963634,0.015131
1,-1,AFG,Afghanistan,Badakhshan,Baharak,163646.498058,161838.336422,85151.767915,52.615326,0.000070,3.464540,0.304174
2,-1,AFG,Afghanistan,Badakhshan,Darwaz,123931.465288,123051.816672,7965.743982,6.473488,0.000070,2.980827,0.300430
3,-1,AFG,Afghanistan,Badakhshan,Fayzabad,456388.436228,429997.228749,348606.782561,81.071867,0.000070,2.395813,0.298038
4,-1,AFG,Afghanistan,Badakhshan,Ishkashim,30028.975282,29910.759535,5750.396696,19.225178,0.000070,2.534993,0.158482

### Description
The SDG Indicator 9.1.1: The Rural Access Index (RAI), 2023 Release data set, part of the SDGI collection, measures the proportion of the rural population who live within 2 kilometers of an all-season road for a given statistical area. UN SDG 9 is "build resilient infrastructure, promote inclusive and sustainable industrialization and foster innovation". Addressing inadequate access to roads, especially in rural areas, is critical to achieving SDG 9. According to the UN Sustainable Transport, Sustainable Development 2021 Interagency Report, sustainable transportation helps to eliminate poverty, promote food security, improve access to key health services, increase trade competitiveness, and bolster human rights. As one measure of progress towards SDG 9, the UN has established SDG indicator 9.1.1. The indicator was computed as the proportion of WorldPop gridded population within 2 kilometers to an OpenStreetMap (OSM) all-season road. The SDG indicator 9.1.1 data set provides estimates for the proportion of the rural population with access to all-season roads for 209 countries and 45,073 subnational Units. The data set is available at both national and level 2 subnational resolutions.

In [2]:
df1.shape

(46690, 12)

In [3]:
import pandas as pd
import requests

# Fetch the data.
df = pd.read_csv("sdgi-9-1-1-rai-2023-national.csv")

df.head()

   OID_ ISO3       NAME_0    SDG911pct    Pct_Error  Shape_Length  Shape_Area
0     1  ABW        Aruba    99.992215     0.489891      0.963634    0.015131
1     2  AFG  Afghanistan    42.939999     0.000070     57.104655   62.749587
2     3  AGO       Angola    53.125903     0.476534     73.800549  103.818655
3     4  AIA     Anguilla    99.500845     2.895000      1.318321    0.007116
4     5  ALA        Åland -9999.000000 -9999.000000     42.556449    0.243777

In [4]:
df.shape

(256, 7)